[package]
name = "Portfolio"
version = "0.1.0"
edition = "2021"

[dependencies]
console_error_panic_hook = "0.1.7"
leptos = { version = "0.7.2", features = ["csr"] }
leptos_meta = "0.7.2"
leptos_router = "0.7.2"
serde = "1.0.216"
